/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("com.android.application")
}

repositories {
    google()
    mavenCentral()
}

android {
    compileSdk = 35  // Updated from compileSdkVersion(35)
    buildToolsVersion = "36.0.0-rc5" 
    // ndkVersion = System.getenv("ANDROID_NDK_VERSION")

    defaultConfig {
        applicationId = "com.arieo.bootstrap"
        namespace = "com.arieo.bootstrap"
        minSdk = 34  // Updated from minSdkVersion(31)
        targetSdk = 35  // Updated from targetSdkVersion(31)
        versionCode = 272
        versionName = "1.1.0"
        // externalNativeBuild {
        //     cmake {
        //         arguments("-DANDROID_TOOLCHAIN=clang", "-DANDROID_STL=c++_shared")
        //         //abiFilters("armeabi-v7a", "arm64-v8a", "x86", "x86_64")
        //         abiFilters("arm64-v8a")
        //     }
        // }
    }

    // Add this dummy project to make sure the -DANDROID_STL=c++_shared works: copy libc++shared.so to jniLibs
    // externalNativeBuild {
    //     cmake {
    //         version = "3.31.9"
    //         path = file("src/main/cpp/CMakeLists.txt")
    //     }
    // }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }

    buildFeatures {
        prefab = true
    }

    packaging {
        jniLibs {
            pickFirsts += "**/*.so"  // If multiple versions exist
            // excludes += "**/libunwanted.so"    // Exclude unwanted libs
        }
    }

    // Add this if you still see configuration cache issues
    configurations.all {
        resolutionStrategy {
            disableDependencyVerification()
        }
    }
}

// // Task to manually copy libc++_shared.so to jniLibs for -DANDROID_STL=c++_shared support
// tasks.register<Copy>("copyLibcppShared") {
//     group = "build setup"
//     description = "Copy libc++_shared.so from NDK to jniLibs for STL support"

//     val jniLibsDir = file("${project.rootDir}/app/src/main/jniLibs/arm64-v8a")
//     // Ensure directory exists
//     jniLibsDir.mkdirs()

//     // NDK path - using ANDROID_SDK_ROOT to match Conan profile configuration
//     val ndkPath = "${System.getenv("ANDROID_SDK_ROOT")}/ndk/${android.ndkVersion}"
    
//     // Alternative NDK structure path (newer NDK versions)
//     val libcppSharedPath = "${ndkPath}/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so"
//     val libcppSharedFile = file(libcppSharedPath)
    
//     // Try to find the file in different possible locations
//     if (libcppSharedFile.exists()) {
//         from(libcppSharedFile)
//         into(jniLibsDir)
//         println("Copying libc++_shared.so from: ${libcppSharedPath}")
//     }
//     else {
//         throw GradleException("Could not find libc++_shared.so in NDK. Please check your NDK installation at: ${ndkPath}")
//     }
    
//     doLast {
//         println("Successfully copied libc++_shared.so to ${jniLibsDir}")
//     }
// }

// // Make sure this task runs before building
// tasks.named("preBuild") 
// { 
//     dependsOn("copyLibcppShared")
// }

dependencies {
    implementation("androidx.appcompat:appcompat:1.4.1")
    // To use the Android Frame Pacing library
    // implementation("androidx.games:games-frame-pacing:2.1.3")

    // To use the Android Performance Tuner
    // implementation("androidx.games:games-performance-tuner:2.0.0")

    // To use the Games Activity library
    implementation("androidx.games:games-activity:4.0.0")

    // To use the Games Controller Library
    // implementation("androidx.games:games-controller:2.0.2")
    
    // APK Expansion library for OBB file handling
    // Using standard Java ZIP support - no external dependency needed
}